#Install apache2 webserver in ubuntu machine
---
- hosts: webserver
  gather_facts: yes
  tasks:
   - name: Install apache2 
     apt: name=httpd state=present
   - name: copy the index file
     copy: src=index.html dest=/var/www/html/index.html
   - name: check apache2 status
     service: name=apache2 state=started
